name: Standard Version Release

on:
  push:
    branches: [ main ]

jobs:
  run_standard_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: git config --global user.email "snode-releaser@fakemail.com"
      - run: git config --global user.name "Auto Snode Releaser"
      - run: yarn
      - run: npm run release
